

# Read URLs from file
# Loop through URLs & collect data

# *Imported the required libraries and packages*

In [ ]:
import requests
import os
from tqdm import tqdm
import time

In [ ]:
os.makedirs("gfp_pages/metrics", exist_ok=True)

# The base URL is "https://www.globalfirepower.com/countries-listing.php"

In [ ]:
base_url = "https://www.globalfirepower.com/countries-listing.php"

other_sources = {
    'https://www.globalfirepower.com/total-population-by-country.php': 'total_population',
        'https://www.globalfirepower.com/available-military-manpower.php': 'total_military_manpower',
        'https://www.globalfirepower.com/manpower-fit-for-military-service.php': 'fit_for_service',
        'https://www.globalfirepower.com/manpower-reaching-military-age-annually.php': 'population_reaching_military_age_annually',
        'https://www.globalfirepower.com/active-military-manpower.php': 'active_personnel',
        'https://www.globalfirepower.com/active-reserve-military-manpower.php': 'reserve_personnel',
        'https://www.globalfirepower.com/manpower-paramilitary.php': 'paramilitary',
        'https://www.globalfirepower.com/aircraft-total.php': 'total_military_aircraft',
        'https://www.globalfirepower.com/aircraft-total-fighters.php': 'fighter_aircraft',
        'https://www.globalfirepower.com/aircraft-total-attack-types.php': 'attack_aircraft',
        'https://www.globalfirepower.com/aircraft-total-transports.php': 'transport_aircraft',
        'https://www.globalfirepower.com/aircraft-total-trainers.php': 'trainer_aircraft',
        'https://www.globalfirepower.com/aircraft-total-special-mission.php': 'special_mission_aircraft',
        'https://www.globalfirepower.com/aircraft-total-tanker-fleet.php': 'tanker_aircraft',
        'https://www.globalfirepower.com/aircraft-helicopters-total.php': 'total_military_helicopters',
        'https://www.globalfirepower.com/aircraft-helicopters-attack.php': 'attack_helicopters',
        'https://www.globalfirepower.com/armor-tanks-total.php': 'tanks',
        'https://www.globalfirepower.com/armor-apc-total.php': 'armored_fighting_vehicles',
        'https://www.globalfirepower.com/armor-self-propelled-guns-total.php': 'self_propelled_artillery',
        'https://www.globalfirepower.com/armor-towed-artillery-total.php': 'towed_artillery',
        'https://www.globalfirepower.com/armor-mlrs-total.php': 'rocket_projectors',
        'https://www.globalfirepower.com/navy-ships.php': 'total_naval_fleet',
        'https://www.globalfirepower.com/navy-force-by-tonnage.php': 'total_naval_fleet_tonnage_mt',
        'https://www.globalfirepower.com/navy-aircraft-carriers.php': 'aircraft_carriers',
        'https://www.globalfirepower.com/navy-helo-carriers.php': 'helicopter_carriers',
        'https://www.globalfirepower.com/navy-submarines.php': 'submarines',
        'https://www.globalfirepower.com/navy-destroyers.php': 'destroyers',
        'https://www.globalfirepower.com/navy-frigates.php': 'frigates',
        'https://www.globalfirepower.com/navy-corvettes.php': 'corvettes',
        'https://www.globalfirepower.com/navy-patrol-coastal-craft.php': 'coastal_patrol_craft',
        'https://www.globalfirepower.com/navy-mine-warfare-craft.php': 'mine_warfare_craft',
        'https://www.globalfirepower.com/defense-spending-budget.php': 'defense_budget_usd',
        'https://www.globalfirepower.com/external-debt-by-country.php': 'external_debt_usd',
        'https://www.globalfirepower.com/purchasing-power-parity.php': 'purchasing_power_parity_usd',
        'https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php': 'foreign_exchange_and_gold_reserves_usd',
        'https://www.globalfirepower.com/major-serviceable-airports-by-country.php': 'total_serviceable_airports',
        'https://www.globalfirepower.com/labor-force-by-country.php': 'labour_force',
        'https://www.globalfirepower.com/major-ports-and-terminals.php': 'major_ports_and_terminals',
        'https://www.globalfirepower.com/merchant-marine-strength-by-country.php': 'total_merchant_marine_fleet',
        'https://www.globalfirepower.com/railway-coverage.php': 'railway_coverage_km',
        'https://www.globalfirepower.com/roadway-coverage.php': 'roadway_coverage_km',
        'https://www.globalfirepower.com/oil-production-by-country.php': 'oil_production_bbl',
        'https://www.globalfirepower.com/oil-consumption-by-country.php': 'oil_consumption_bbl',
        'https://www.globalfirepower.com/proven-oil-reserves-by-country.php': 'proven_oil_reserves_bbl',
        'https://www.globalfirepower.com/natural-gas-production-by-country.php': 'natural_gas_production_cum',
        'https://www.globalfirepower.com/natural-gas-consumption-by-country.php': 'natural_gas_consumption_cum',
        'https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php': 'proven_natural_gas_reserves_cum',
        'https://www.globalfirepower.com/coal-production-by-country.php': 'coal_production_cum',
        'https://www.globalfirepower.com/coal-consumption-by-country.php': 'coal_consumption_mt',
        'https://www.globalfirepower.com/proven-coal-reserves-by-country.php': 'proven_coal_reserves_cum',
        'https://www.globalfirepower.com/square-land-area.php': 'total_land_area_sq_km',
        'https://www.globalfirepower.com/coastline-coverage.php': 'coastline_coverage_km',
        'https://www.globalfirepower.com/border-coverage.php': 'border_coverage_km',
        'https://www.globalfirepower.com/waterway-coverage.php': 'waterway_coverage_km'
}

# This function fetches a webpage from the given URL and saves its HTML content to a file, handling errors and failed requests.

In [ ]:
def download_page(url, filename):
    try:
        res = requests.get(url, timeout=15)
        if res.status_code == 200:
            with open(filename, "w", encoding="utf-8") as f:
                f.write(res.text)
        else:
            print(f"Failed: {url}")
    except Exception as e:
        print(f"Error {url} -> {e}")

# This is exactly how you would save a webpage before scraping its content.

In [ ]:
download_page(base_url, "gfp_pages/countries_listing.html")

# This loop downloads multiple webpages from other_sources, saves them in gfp_pages/metrics/, and shows a progress bar with a 2-second delay between requests.

In [ ]:
for url, name in tqdm(other_sources.items()):
    filepath = f"gfp_pages/metrics/{name}.html"
    download_page(url, filepath)
    time.sleep(2)

100%|██████████| 54/54 [01:55<00:00,  2.14s/it]

In [ ]:
from bs4 import BeautifulSoup
import pandas as pd
import os
from tqdm import tqdm
import re

In [ ]:
METRIC_FOLDER = "gfp_pages/metrics"

In [ ]:
files = [f for f in os.listdir(METRIC_FOLDER) if f.endswith(".html")]
files

['fighter_aircraft.html',
 'oil_production_bbl.html',
 'destroyers.html',
 'coastal_patrol_craft.html',
 'railway_coverage_km.html',
 'special_mission_aircraft.html',
 'natural_gas_consumption_cum.html',
 'trainer_aircraft.html',
 'total_naval_fleet.html',
 'fit_for_service.html',
 'defense_budget_usd.html',
 'self_propelled_artillery.html',
 'total_military_helicopters.html',
 'proven_oil_reserves_bbl.html',
 'border_coverage_km.html',
 'corvettes.html',
 'attack_aircraft.html',
 'major_ports_and_terminals.html',
 'population_reaching_military_age_annually.html',
 'total_military_manpower.html',
 'natural_gas_production_cum.html',
 'frigates.html',
 'submarines.html',
 'helicopter_carriers.html',
 'total_naval_fleet_tonnage_mt.html',
 'total_military_aircraft.html',
 'foreign_exchange_and_gold_reserves_usd.html',
 'attack_helicopters.html',
 'labour_force.html',
 'total_population.html',
 'proven_natural_gas_reserves_cum.html',
 'total_serviceable_airports.html',
 'mine_warfare_craft.html',
 'armored_fighting_vehicles.html',
 'tanks.html',
 'reserve_personnel.html',
 'coal_consumption_mt.html',
 'tanker_aircraft.html',
 'purchasing_power_parity_usd.html',
 'active_personnel.html',
 'rocket_projectors.html',
 'paramilitary.html',
 'towed_artillery.html',
 'transport_aircraft.html',
 'oil_consumption_bbl.html',
 'roadway_coverage_km.html',
 'external_debt_usd.html',
 'total_land_area_sq_km.html',
 'coastline_coverage_km.html',
 'proven_coal_reserves_cum.html',
 'waterway_coverage_km.html',
 'aircraft_carriers.html',
 'total_merchant_marine_fleet.html',
 'coal_production_cum.html']

In [ ]:
with open("gfp_pages/metrics/tanks.html") as f:
    content = f.read()

# This reads the entire file into the variable content in one step

In [ ]:
soup = BeautifulSoup(content, "html.parser")

# This safely extracts the text without crashing if no (span) exists.

In [ ]:
soup.find("span")

# Returns None for None input; otherwise strips commas/spaces, extracts the first number and unit with regex, and joins them into a single string.

In [ ]:
# Unit Parser
def unit(raw_text):
    if raw_text is None:
        return None

    text = raw_text.replace(",", "").strip()

    number_match = re.search(r"[\d.]+", text)
    number = number_match.group() if number_match else ""

    unit_match = re.search(r"[a-zA-Z%./]+", text)
    unit = unit_match.group() if unit_match else ""

    return f"{number} {unit}".strip()

# Reads an HTML file, finds all metric cards, extracts each card’s country and metric value using the unit parser, and returns a DataFrame with countries and the specified metric.

In [ ]:
def parse_metric_cards(filepath, metric_name):
    with open(filepath, "r", encoding="utf-8") as f:
        soup = BeautifulSoup(f, "lxml")

    cards = soup.find_all("div", class_="recordsetContainer")
    data = []

    for card in cards:
        # country name
        country_tag = card.find("div", class_="longFormName")
        if not country_tag:
            continue
        country = country_tag.get_text(strip=True)

        # metrics values
        value_tag = card.find("div", class_="valueContainer")
        if not value_tag:
            continue

        # units
        raw_text = value_tag.get_text(" ", strip=True)
        value = unit(raw_text)

        data.append([country, value])

    df = pd.DataFrame(data, columns=["country", metric_name])
    return df

# Parses the HTML file `"gfp_pages/metrics/coal_production_cum.html"` for metric cards labeled `"tanks"`, stores the results in `df_test`, and displays the first few rows of that DataFrame.

In [ ]:
test_file = "gfp_pages/metrics/coal_production_cum.html"
df_test = parse_metric_cards(test_file, "tanks")
df_test.head()

         country            tanks
0          China  4805000000 Cu.M
1          India  1020000000 Cu.M
2      Indonesia   783453000 Cu.M
3  United States   534234000 Cu.M
4         Russia   531130000 Cu.M

#Iterates over all HTML files in the metrics folder, parses each into a DataFrame using its filename as the metric name, and merges them all on `country` to build a combined `master_df`.

In [ ]:
METRIC_FOLDER = "gfp_pages/metrics"
files = [f for f in os.listdir(METRIC_FOLDER) if f.endswith(".html")]

master_df = None

for file in tqdm(files):
    metric_name = file.replace(".html", "")
    filepath = os.path.join(METRIC_FOLDER, file)

    df_metric = parse_metric_cards(filepath, metric_name)

    if master_df is None:
        master_df = df_metric
    else:
        master_df = pd.merge(master_df, df_metric, on="country", how="outer")

100%|██████████| 54/54 [00:07<00:00,  6.92it/s]

# print(master_df.shape) displays the number of rows and columns in master_df, and master_df.head() shows the first 5 rows of the DataFrame.

# So together, it checks the size of the DataFrame and previews its top rows.

In [ ]:
print(master_df.shape)
master_df.head()

(145, 55)

,country,fighter_aircraft,oil_production_bbl,destroyers,coastal_patrol_craft,railway_coverage_km,special_mission_aircraft,natural_gas_consumption_cum,trainer_aircraft,total_naval_fleet,...,oil_consumption_bbl,roadway_coverage_km,external_debt_usd,total_land_area_sq_km,coastline_coverage_km,proven_coal_reserves_cum,waterway_coverage_km,aircraft_carriers,total_merchant_marine_fleet,coal_production_cum
0,Afghanistan,0,0 bbl,0,0,0 km,0,80200000 Cu.M,0,0,...,58000 bbl,34903 km,1929750000,652230 km,0 km,66000000 Cu.M,1200 km,0,0,767000 Cu.M
1,Albania,0,14000 bbl,0,33,424 km,0,50623000 Cu.M,0,33,...,21000 bbl,3581 km,5363000000,28748 km,362 km,522000000 Cu.M,41 km,0,69,473000 Cu.M
2,Algeria,111,1443000 bbl,0,75,4020 km,10,47963000000 Cu.M,90,111,...,446000 bbl,112696 km,4764000000,2381740 km,998 km,233000000 Cu.M,0 km,0,119,0 Cu.M
3,Angola,67,1175000 bbl,0,32,2761 km,2,1397000000 Cu.M,56,32,...,121000 bbl,76000 km,45299000000,1246700 km,1600 km,0 Cu.M,1300 km,0,64,0 Cu.M
4,Argentina,23,807000 bbl,3,13,17866 km,13,46228000000 Cu.M,71,42,...,749000 bbl,240000 km,74362000000,2780400 km,4989 km,799999000 Cu.M,11000 km,0,201,869000 Cu.M

# Saves the master_df DataFrame to a CSV file named "military_raw_collected.csv" without including row indices.

In [ ]:
master_df.to_csv("military_raw_collected.csv", index=False)

# Reads the CSV file "military_raw_collected.csv" into a DataFrame df and displays the first few rows.

In [ ]:
import pandas as pd
import re

df = pd.read_csv("military_raw_collected.csv")
df.head()

,country,fighter_aircraft,oil_production_bbl,destroyers,coastal_patrol_craft,railway_coverage_km,special_mission_aircraft,natural_gas_consumption_cum,trainer_aircraft,total_naval_fleet,...,oil_consumption_bbl,roadway_coverage_km,external_debt_usd,total_land_area_sq_km,coastline_coverage_km,proven_coal_reserves_cum,waterway_coverage_km,aircraft_carriers,total_merchant_marine_fleet,coal_production_cum
0,Afghanistan,0,0 bbl,0,0,0 km,0,80200000 Cu.M,0,0,...,58000 bbl,34903 km,1929750000,652230 km,0 km,66000000 Cu.M,1200 km,0,0,767000 Cu.M
1,Albania,0,14000 bbl,0,33,424 km,0,50623000 Cu.M,0,33,...,21000 bbl,3581 km,5363000000,28748 km,362 km,522000000 Cu.M,41 km,0,69,473000 Cu.M
2,Algeria,111,1443000 bbl,0,75,4020 km,10,47963000000 Cu.M,90,111,...,446000 bbl,112696 km,4764000000,2381740 km,998 km,233000000 Cu.M,0 km,0,119,0 Cu.M
3,Angola,67,1175000 bbl,0,32,2761 km,2,1397000000 Cu.M,56,32,...,121000 bbl,76000 km,45299000000,1246700 km,1600 km,0 Cu.M,1300 km,0,64,0 Cu.M
4,Argentina,23,807000 bbl,3,13,17866 km,13,46228000000 Cu.M,71,42,...,749000 bbl,240000 km,74362000000,2780400 km,4989 km,799999000 Cu.M,11000 km,0,201,869000 Cu.M

# Looks up the row for the given country in df, and if found returns it transposed with the country as the column name; otherwise returns "Country not found"

In [ ]:
# metrics for any country
def get_country_metrics(country_name):
    row = df[df["country"] == country_name]
    if row.empty:
        return "Country not found"
    result = row.T
    result.columns = [country_name]
    return result

# Calls the get_country_metrics function with "India" as input and returns India’s metrics.

In [ ]:
get_country_metrics("India")

                                                        India
country                                                 India
fighter_aircraft                                          476
oil_production_bbl                                 822000 bbl
destroyers                                                 13
coastal_patrol_craft                                      146
railway_coverage_km                                  65554 km
special_mission_aircraft                                   72
natural_gas_consumption_cum                  58867000000 Cu.M
trainer_aircraft                                          334
total_naval_fleet                                         343
fit_for_service                                     522786598
defense_budget_usd                               109000000000
self_propelled_artillery                                  100
total_military_helicopters                                594
proven_oil_reserves_bbl                        4605000000 bbl
border_coverage_km                                   13888 km
corvettes                                                  21
attack_aircraft                                           124
major_ports_and_terminals                                  56
population_reaching_military_age_annually            23955181
total_military_manpower                             662290299
natural_gas_production_cum                   33170000000 Cu.M
frigates                                                   18
submarines                                                 18
helicopter_carriers                                         0
total_naval_fleet_tonnage_mt                         631989.0
total_military_aircraft                                  2183
foreign_exchange_and_gold_reserves_usd           643043000000
attack_helicopters                                         79
labour_force                                        607691000
total_population                                   1409128296
proven_natural_gas_reserves_cum            1381000000000 Cu.M
total_serviceable_airports                                315
mine_warfare_craft                                          0
armored_fighting_vehicles                              163554
tanks                                                    3913
reserve_personnel                                     1000000
coal_consumption_mt                             1262000000 mt
tanker_aircraft                                             6
purchasing_power_parity_usd                    14244000000000
active_personnel                                      1431000
rocket_projectors                                         300
paramilitary                                          2527000
towed_artillery                                          5640
transport_aircraft                                        277
oil_consumption_bbl                               5271000 bbl
roadway_coverage_km                                6371847 km
external_debt_usd                                212728000000
total_land_area_sq_km                              3287263 km
coastline_coverage_km                                 7000 km
proven_coal_reserves_cum                    127727000000 Cu.M
waterway_coverage_km                                 14500 km
aircraft_carriers                                           2
total_merchant_marine_fleet                              1859
coal_production_cum                           1020000000 Cu.M

# Returns 0 for NaN input; otherwise extracts the first number from the text and converts it to an integer, or 0 if no number is found.

In [ ]:
def extract_number(text):
    if pd.isna(text):
        return 0
    match = re.search(r"\d+", str(text))
    return int(match.group()) if match else 0

# Applies extract_number to the aircraft_carriers column and stores the resulting numbers in a new column aircraft_carriers_num

In [ ]:
df["aircraft_carriers_num"] = df["aircraft_carriers"].apply(extract_number)

# Sorts the DataFrame by aircraft_carriers_num descending, selects only country and aircraft_carriers_num columns, and returns the top 10 rows.

In [ ]:
top10 = (
    df.sort_values(by="aircraft_carriers_num", ascending=False)
      [["country", "aircraft_carriers_num"]]
      .head(10)
)

top10

            country  aircraft_carriers_num
137   United States                     11
28            China                      3
59            Italy                      2
53            India                      2
136  United Kingdom                      2
43           France                      1
119           Spain                      1
107          Russia                      1
8        Azerbaijan                      0
1           Albania                      0