### Data Cleaning & Standardization

Load Raw Data & Basic Analysis

This step loads the raw scraped military dataset

In [ ]:
import pandas as pd
df = pd.read_csv("military data.csv")

The dataset was successfully loaded and inspected.

Performs an initial inspection to understand its structure, column names, and data types.

In [ ]:
print(df.head())
print(df.info())

       country  active_personnel  aircraft_carriers  \
0  Afghanistan             75000                  0
1      Albania              7500                  0
2      Algeria            130000                  0
3       Angola            107000                  0
4    Argentina            108000                  0

   armored_fighting_vehicles  attack_aircraft  attack_helicopters  \
0                       3902                0                   0
1                       1492                0                   0
2                      24920               42                  74
3                       2258                6                  14
4                      22432               11                   0

  border_coverage_km coal_consumption_mt coal_production_cum  \
0            5987 km           503000 mt         767000 Cu.M
1             691 km           255000 mt         473000 Cu.M
2            6734 km             3000 mt              0 Cu.M
3            5369 km                0 mt              0 Cu.M
4           11968 km          2534000 mt         869000 Cu.M

   coastal_patrol_craft  ... total_military_helicopters  \
0                     0  ...                          3
1                    33  ...                         19
2                    75  ...                        300
3                    32  ...                        115
4                    13  ...                         96

   total_military_manpower  total_naval_fleet  total_naval_fleet_tonnage_mt  \
0                 15647405                  0                           NaN
1                  1522479                 33                           NaN
2                 22570787                111                       83480.0
3                  7440412                 32                           NaN
4                 20677529                 42                      122128.0

   total_population  total_serviceable_airports  towed_artillery  \
0          40121552                          68                0
1           3107100                           3                0
2          47022473                          95              483
3          37202061                         107              575
4          46994384                         764              172

   trainer_aircraft  transport_aircraft  waterway_coverage_km
0                 0                   2               1200 km
1                 0                   1                 41 km
2                90                  63                  0 km
3                56                  32               1300 km
4                71                  25              11000 km

[5 rows x 55 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 55 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    145 non-null    object
 1   active_personnel                           145 non-null    int64
 2   aircraft_carriers                          145 non-null    int64
 3   armored_fighting_vehicles                  145 non-null    int64
 4   attack_aircraft                            145 non-null    int64
 5   attack_helicopters                         145 non-null    int64
 6   border_coverage_km                         145 non-null    object
 7   coal_consumption_mt                        145 non-null    object
 8   coal_production_cum                        145 non-null    object
 9   coastal_patrol_craft                       145 non-null    int64
 10  coastline_coverage_km                      145 non-null    object
 11  corvettes                                  145 non-null    int64
 12  defense_budget_usd                         145 non-null    int64
 13  destroyers                                 145 non-null    int64
 14  external_debt_usd                          145 non-null    int64
 15  fighter_aircraft                           145 non-null    int64
 16  fit_for_service                            145 non-null    int64
 17  foreign_exchange_and_gold_reserves_usd     145 non-null    int64
 18  frigates                                   145 non-null    int64
 19  helicopter_carriers                        145 non-null    int64
 20  labour_force                               145 non-null    int64
 21  major_ports_and_terminals                  145 non-null    int64
 22  mine_warfare_craft                         145 non-null    int64
 23  natural_gas_consumption_cum                145 non-null    object
 24  natural_gas_production_cum                 145 non-null    object
 25  oil_consumption_bbl                        145 non-null    object
 26  oil_production_bbl                         145 non-null    object
 27  paramilitary                               145 non-null    int64
 28  population_reaching_military_age_annually  145 non-null    int64
 29  proven_coal_reserves_cum                   145 non-null    object
 30  proven_natural_gas_reserves_cum            145 non-null    object
 31  proven_oil_reserves_bbl                    145 non-null    object
 32  purchasing_power_parity_usd                145 non-null    int64
 33  railway_coverage_km                        145 non-null    object
 34  reserve_personnel                          145 non-null    int64
 35  roadway_coverage_km                        145 non-null    object
 36  rocket_projectors                          145 non-null    int64
 37  self_propelled_artillery                   145 non-null    int64
 38  special_mission_aircraft                   145 non-null    int64
 39  submarines                                 145 non-null    int64
 40  tanker_aircraft                            145 non-null    int64
 41  tanks                                      145 non-null    int64
 42  total_land_area_sq_km                      145 non-null    object
 43  total_merchant_marine_fleet                145 non-null    int64
 44  total_military_aircraft                    145 non-null    int64
 45  total_military_helicopters                 145 non-null    int64
 46  total_military_manpower                    145 non-null    int64
 47  total_naval_fleet                          145 non-null    int64
 48  total_naval_fleet_tonnage_mt               51 non-null     float64
 49  total_population                           145 non-null    int64
 50  total_serviceable_airports                 145 non-null    int64
 51  towed_artillery                            145 non-null    int64
 52  trainer_aircraft                           145 non-null    int64
 53  transport_aircraft                         145 non-null    int64
 54  waterway_coverage_km                       145 non-null    object
dtypes: float64(1), int64(38), object(16)
memory usage: 62.4+ KB
None

Several numeric columns were stored as object type and required cleaning.

Identify Data Noise: This step reviews column names and data types to identify noisy fields and incorrect formats.

In [ ]:
df.columns.tolist()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 55 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    145 non-null    object
 1   active_personnel                           145 non-null    int64
 2   aircraft_carriers                          145 non-null    int64
 3   armored_fighting_vehicles                  145 non-null    int64
 4   attack_aircraft                            145 non-null    int64
 5   attack_helicopters                         145 non-null    int64
 6   border_coverage_km                         145 non-null    object
 7   coal_consumption_mt                        145 non-null    object
 8   coal_production_cum                        145 non-null    object
 9   coastal_patrol_craft                       145 non-null    int64
 10  coastline_coverage_km                      145 non-null    object
 11  corvettes                                  145 non-null    int64
 12  defense_budget_usd                         145 non-null    int64
 13  destroyers                                 145 non-null    int64
 14  external_debt_usd                          145 non-null    int64
 15  fighter_aircraft                           145 non-null    int64
 16  fit_for_service                            145 non-null    int64
 17  foreign_exchange_and_gold_reserves_usd     145 non-null    int64
 18  frigates                                   145 non-null    int64
 19  helicopter_carriers                        145 non-null    int64
 20  labour_force                               145 non-null    int64
 21  major_ports_and_terminals                  145 non-null    int64
 22  mine_warfare_craft                         145 non-null    int64
 23  natural_gas_consumption_cum                145 non-null    object
 24  natural_gas_production_cum                 145 non-null    object
 25  oil_consumption_bbl                        145 non-null    object
 26  oil_production_bbl                         145 non-null    object
 27  paramilitary                               145 non-null    int64
 28  population_reaching_military_age_annually  145 non-null    int64
 29  proven_coal_reserves_cum                   145 non-null    object
 30  proven_natural_gas_reserves_cum            145 non-null    object
 31  proven_oil_reserves_bbl                    145 non-null    object
 32  purchasing_power_parity_usd                145 non-null    int64
 33  railway_coverage_km                        145 non-null    object
 34  reserve_personnel                          145 non-null    int64
 35  roadway_coverage_km                        145 non-null    object
 36  rocket_projectors                          145 non-null    int64
 37  self_propelled_artillery                   145 non-null    int64
 38  special_mission_aircraft                   145 non-null    int64
 39  submarines                                 145 non-null    int64
 40  tanker_aircraft                            145 non-null    int64
 41  tanks                                      145 non-null    int64
 42  total_land_area_sq_km                      145 non-null    object
 43  total_merchant_marine_fleet                145 non-null    int64
 44  total_military_aircraft                    145 non-null    int64
 45  total_military_helicopters                 145 non-null    int64
 46  total_military_manpower                    145 non-null    int64
 47  total_naval_fleet                          145 non-null    int64
 48  total_naval_fleet_tonnage_mt               51 non-null     float64
 49  total_population                           145 non-null    int64
 50  total_serviceable_airports                 145 non-null    int64
 51  towed_artillery                            145 non-null    int64
 52  trainer_aircraft                           145 non-null    int64
 53  transport_aircraft                         145 non-null    int64
 54  waterway_coverage_km                       145 non-null    object
dtypes: float64(1), int64(38), object(16)
memory usage: 62.4+ KB

Column inspection confirmed the presence of text-formatted numeric values and inconsistent column formatting.

Clean Numeric Columns: This step removes non-numeric characters such as symbols, commas, and units from numeric columns and converts them into float format.

In [ ]:
def clean_numeric(col):
    return (
        col.astype(str)
           .str.replace(r'[^0-9.]', '', regex=True)
           .replace('', '0')
           .astype(float)
    )

for col in df.columns:
    if col != 'country':
        df[col] = clean_numeric(df[col])

All numeric columns were cleaned and converted into proper numerical format, making them suitable for analysis.

Standardize Column Names: This step standardizes column names by removing extra spaces and converting them to lowercase for consistency.

In [ ]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
)

Column names were standardized to maintain consistency across the dataset.

Handle Missing Values: This step handles missing values to prevent errors during KPI calculations.

In [ ]:
df = df.fillna(0)

Missing values were replaced with zero to maintain dataset completeness.

Validate Cleaned Data: This step validates the cleaned dataset by checking data types, missing values, duplicates, and statistical summaries.

In [ ]:
df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 55 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    145 non-null    object
 1   active_personnel                           145 non-null    float64
 2   aircraft_carriers                          145 non-null    float64
 3   armored_fighting_vehicles                  145 non-null    float64
 4   attack_aircraft                            145 non-null    float64
 5   attack_helicopters                         145 non-null    float64
 6   border_coverage_km                         145 non-null    float64
 7   coal_consumption_mt                        145 non-null    float64
 8   coal_production_cum                        145 non-null    float64
 9   coastal_patrol_craft                       145 non-null    float64
 10  coastline_coverage_km                      145 non-null    float64
 11  corvettes                                  145 non-null    float64
 12  defense_budget_usd                         145 non-null    float64
 13  destroyers                                 145 non-null    float64
 14  external_debt_usd                          145 non-null    float64
 15  fighter_aircraft                           145 non-null    float64
 16  fit_for_service                            145 non-null    float64
 17  foreign_exchange_and_gold_reserves_usd     145 non-null    float64
 18  frigates                                   145 non-null    float64
 19  helicopter_carriers                        145 non-null    float64
 20  labour_force                               145 non-null    float64
 21  major_ports_and_terminals                  145 non-null    float64
 22  mine_warfare_craft                         145 non-null    float64
 23  natural_gas_consumption_cum                145 non-null    float64
 24  natural_gas_production_cum                 145 non-null    float64
 25  oil_consumption_bbl                        145 non-null    float64
 26  oil_production_bbl                         145 non-null    float64
 27  paramilitary                               145 non-null    float64
 28  population_reaching_military_age_annually  145 non-null    float64
 29  proven_coal_reserves_cum                   145 non-null    float64
 30  proven_natural_gas_reserves_cum            145 non-null    float64
 31  proven_oil_reserves_bbl                    145 non-null    float64
 32  purchasing_power_parity_usd                145 non-null    float64
 33  railway_coverage_km                        145 non-null    float64
 34  reserve_personnel                          145 non-null    float64
 35  roadway_coverage_km                        145 non-null    float64
 36  rocket_projectors                          145 non-null    float64
 37  self_propelled_artillery                   145 non-null    float64
 38  special_mission_aircraft                   145 non-null    float64
 39  submarines                                 145 non-null    float64
 40  tanker_aircraft                            145 non-null    float64
 41  tanks                                      145 non-null    float64
 42  total_land_area_sq_km                      145 non-null    float64
 43  total_merchant_marine_fleet                145 non-null    float64
 44  total_military_aircraft                    145 non-null    float64
 45  total_military_helicopters                 145 non-null    float64
 46  total_military_manpower                    145 non-null    float64
 47  total_naval_fleet                          145 non-null    float64
 48  total_naval_fleet_tonnage_mt               145 non-null    float64
 49  total_population                           145 non-null    float64
 50  total_serviceable_airports                 145 non-null    float64
 51  towed_artillery                            145 non-null    float64
 52  trainer_aircraft                           145 non-null    float64
 53  transport_aircraft                         145 non-null    float64
 54  waterway_coverage_km                       145 non-null    float64
dtypes: float64(54), object(1)
memory usage: 62.4+ KB

np.int64(0)

The dataset was validated successfully, ensuring no missing values, no duplicates, and correct data types.

Export Cleaned Dataset: This step exports the cleaned dataset for further KPI engineering.

In [ ]:
df.to_csv("military_data_cleaned.csv", index=False)

The cleaned dataset was exported successfully for advanced analysis.

FOR CHECKING

In [ ]:
print(df.isnull().sum())
print(df.dtypes)
print(df.duplicated().sum())

country                                      0
active_personnel                             0
aircraft_carriers                            0
armored_fighting_vehicles                    0
attack_aircraft                              0
attack_helicopters                           0
border_coverage_km                           0
coal_consumption_mt                          0
coal_production_cum                          0
coastal_patrol_craft                         0
coastline_coverage_km                        0
corvettes                                    0
defense_budget_usd                           0
destroyers                                   0
external_debt_usd                            0
fighter_aircraft                             0
fit_for_service                              0
foreign_exchange_and_gold_reserves_usd       0
frigates                                     0
helicopter_carriers                          0
labour_force                                 0
major_ports_and_terminals                    0
mine_warfare_craft                           0
natural_gas_consumption_cum                  0
natural_gas_production_cum                   0
oil_consumption_bbl                          0
oil_production_bbl                           0
paramilitary                                 0
population_reaching_military_age_annually    0
proven_coal_reserves_cum                     0
proven_natural_gas_reserves_cum              0
proven_oil_reserves_bbl                      0
purchasing_power_parity_usd                  0
railway_coverage_km                          0
reserve_personnel                            0
roadway_coverage_km                          0
rocket_projectors                            0
self_propelled_artillery                     0
special_mission_aircraft                     0
submarines                                   0
tanker_aircraft                              0
tanks                                        0
total_land_area_sq_km                        0
total_merchant_marine_fleet                  0
total_military_aircraft                      0
total_military_helicopters                   0
total_military_manpower                      0
total_naval_fleet                            0
total_naval_fleet_tonnage_mt                 0
total_population                             0
total_serviceable_airports                   0
towed_artillery                              0
trainer_aircraft                             0
transport_aircraft                           0
waterway_coverage_km                         0
dtype: int64
country                                       object
active_personnel                             float64
aircraft_carriers                            float64
armored_fighting_vehicles                    float64
attack_aircraft                              float64
attack_helicopters                           float64
border_coverage_km                           float64
coal_consumption_mt                          float64
coal_production_cum                          float64
coastal_patrol_craft                         float64
coastline_coverage_km                        float64
corvettes                                    float64
defense_budget_usd                           float64
destroyers                                   float64
external_debt_usd                            float64
fighter_aircraft                             float64
fit_for_service                              float64
foreign_exchange_and_gold_reserves_usd       float64
frigates                                     float64
helicopter_carriers                          float64
labour_force                                 float64
major_ports_and_terminals                    float64
mine_warfare_craft                           float64
natural_gas_consumption_cum                  float64
natural_gas_production_cum                   float64
oil_consumption_bbl                          float64
oil_production_bbl                           float64
paramilitary                                 float64
population_reaching_military_age_annually    float64
proven_coal_reserves_cum                     float64
proven_natural_gas_reserves_cum              float64
proven_oil_reserves_bbl                      float64
purchasing_power_parity_usd                  float64
railway_coverage_km                          float64
reserve_personnel                            float64
roadway_coverage_km                          float64
rocket_projectors                            float64
self_propelled_artillery                     float64
special_mission_aircraft                     float64
submarines                                   float64
tanker_aircraft                              float64
tanks                                        float64
total_land_area_sq_km                        float64
total_merchant_marine_fleet                  float64
total_military_aircraft                      float64
total_military_helicopters                   float64
total_military_manpower                      float64
total_naval_fleet                            float64
total_naval_fleet_tonnage_mt                 float64
total_population                             float64
total_serviceable_airports                   float64
towed_artillery                              float64
trainer_aircraft                             float64
transport_aircraft                           float64
waterway_coverage_km                         float64
dtype: object
0


### KPI Engineering & Feature Creation

Load Clean Dataset: This step loads the cleaned dataset to begin KPI engineering.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("military_data_cleaned.csv")
print(df.head())

       country  active_personnel  aircraft_carriers  \
0  Afghanistan           75000.0                0.0
1      Albania            7500.0                0.0
2      Algeria          130000.0                0.0
3       Angola          107000.0                0.0
4    Argentina          108000.0                0.0

   armored_fighting_vehicles  attack_aircraft  attack_helicopters  \
0                     3902.0              0.0                 0.0
1                     1492.0              0.0                 0.0
2                    24920.0             42.0                74.0
3                     2258.0              6.0                14.0
4                    22432.0             11.0                 0.0

   border_coverage_km  coal_consumption_mt  coal_production_cum  \
0              5987.0             503000.0             767000.0
1               691.0             255000.0             473000.0
2              6734.0               3000.0                  0.0
3              5369.0                  0.0                  0.0
4             11968.0            2534000.0             869000.0

   coastal_patrol_craft  ...  total_military_helicopters  \
0                   0.0  ...                         3.0
1                  33.0  ...                        19.0
2                  75.0  ...                       300.0
3                  32.0  ...                       115.0
4                  13.0  ...                        96.0

   total_military_manpower  total_naval_fleet  total_naval_fleet_tonnage_mt  \
0               15647405.0                0.0                           0.0
1                1522479.0               33.0                           0.0
2               22570787.0              111.0                       83480.0
3                7440412.0               32.0                           0.0
4               20677529.0               42.0                      122128.0

   total_population  total_serviceable_airports  towed_artillery  \
0        40121552.0                        68.0              0.0
1         3107100.0                         3.0              0.0
2        47022473.0                        95.0            483.0
3        37202061.0                       107.0            575.0
4        46994384.0                       764.0            172.0

   trainer_aircraft  transport_aircraft  waterway_coverage_km
0               0.0                 2.0                1200.0
1               0.0                 1.0                  41.0
2              90.0                63.0                   0.0
3              56.0                32.0                1300.0
4              71.0                25.0               11000.0

[5 rows x 55 columns]

The cleaned dataset was loaded successfully and is ready for KPI creation.

Define Required KPIs

Assets per Capita   (total_aircraft + tanks + naval_assets) / total_manpower.   This step calculates Assets per Capita to measure total military assets relative to total manpower.

In [ ]:
df["assets_per_capita"] = (
    df["total_military_aircraft"] +
    df["tanks"] +
    df["total_naval_fleet"]
) / df["total_military_manpower"].replace(0, np.nan)

Assets per Capita was successfully computed as an indicator of equipment strength.

Budget-to-GDP Ratio   defense_budget / gdp. This step computes Budget-to-GDP Ratio to evaluate defense spending relative to economic strength.

In [ ]:
df["budget_to_gdp_ratio"] = (
    df["defense_budget_usd"] /
    df["purchasing_power_parity_usd"].replace(0, np.nan)
)

Budget-to-GDP Ratio was derived to assess defense investment intensity.

Power Index Rank Gaprank(country) – rank(top_country). This step ranks countries based on defense budget and calculates the rank gap compared to the top country.

In [ ]:
df["rank"] = df["defense_budget_usd"].rank(ascending=False)

top_rank = df["rank"].min()

df["power_index_rank_gap"] = df["rank"] - top_rank

Ranking and rank gap were successfully computed to support comparative analysis.

KPI Calculations

Assets per Capita    (total_aircraft + tanks + naval_assets) / total_manpower. This step validates the engineered KPIs by checking for infinite values and reviewing statistical ranges.

In [ ]:
df["assets_per_capita"] = (
    df["total_military_aircraft"] +
    df["tanks"] +
    df["total_naval_fleet"]
) / df["total_military_manpower"].replace(0, np.nan)

Budget-to-GDP Ratio defense_budget / gdp

In [ ]:
df["budget_to_gdp_ratio"] = (
    df["defense_budget_usd"] /
    df["purchasing_power_parity_usd"].replace(0, np.nan)
)

Power Index Rank Gap

In [ ]:
df["rank"] = df["defense_budget_usd"].rank(ascending=False)

In [ ]:
top_rank = df["rank"].min()

In [ ]:
df["power_index_rank_gap"] = df["rank"] - top_rank

Metadata Enrichment

Strength Category Based on Assets per Capita ,This step categorizes countries into strength tiers based on Assets per Capita.

In [ ]:
df["strength_category"] = pd.cut(
    df["assets_per_capita"],
    bins=3,
    labels=["Low", "Medium", "High"]
)

Countries were categorized into Low, Medium, and High strength tiers.

Validate KPI Values

Check division by zero, This step validates the KPI calculations by checking for division-by-zero errors. During KPI computation, division operations may produce infinite values if the denominator is zero. Therefore, we inspect all numeric columns to ensure no infinite values exist.

In [ ]:
import numpy as np

print("Infinite values check:\n")
print(np.isinf(df.select_dtypes(include=[float, int])).sum())

Infinite values check:

active_personnel                             0
aircraft_carriers                            0
armored_fighting_vehicles                    0
attack_aircraft                              0
attack_helicopters                           0
border_coverage_km                           0
coal_consumption_mt                          0
coal_production_cum                          0
coastal_patrol_craft                         0
coastline_coverage_km                        0
corvettes                                    0
defense_budget_usd                           0
destroyers                                   0
external_debt_usd                            0
fighter_aircraft                             0
fit_for_service                              0
foreign_exchange_and_gold_reserves_usd       0
frigates                                     0
helicopter_carriers                          0
labour_force                                 0
major_ports_and_terminals                    0
mine_warfare_craft                           0
natural_gas_consumption_cum                  0
natural_gas_production_cum                   0
oil_consumption_bbl                          0
oil_production_bbl                           0
paramilitary                                 0
population_reaching_military_age_annually    0
proven_coal_reserves_cum                     0
proven_natural_gas_reserves_cum              0
proven_oil_reserves_bbl                      0
purchasing_power_parity_usd                  0
railway_coverage_km                          0
reserve_personnel                            0
roadway_coverage_km                          0
rocket_projectors                            0
self_propelled_artillery                     0
special_mission_aircraft                     0
submarines                                   0
tanker_aircraft                              0
tanks                                        0
total_land_area_sq_km                        0
total_merchant_marine_fleet                  0
total_military_aircraft                      0
total_military_helicopters                   0
total_military_manpower                      0
total_naval_fleet                            0
total_naval_fleet_tonnage_mt                 0
total_population                             0
total_serviceable_airports                   0
towed_artillery                              0
trainer_aircraft                             0
transport_aircraft                           0
waterway_coverage_km                         0
assets_per_capita                            0
budget_to_gdp_ratio                          0
rank                                         0
power_index_rank_gap                         0
dtype: int64

The output confirms whether any infinite values are present in the dataset. If all values are zero, it indicates that no division-by-zero errors occurred and the KPI calculations are numerically valid.

Verify Realistic Ranges, This step checks the statistical summary of the KPIs to ensure the values are within logical ranges.

In [ ]:
print("\nKPI Statistics:\n")
print(df[[
    "assets_per_capita",
    "budget_to_gdp_ratio",
    "power_index_rank_gap"
]].describe())

KPI Statistics:

       assets_per_capita  budget_to_gdp_ratio  power_index_rank_gap
count         145.000000           145.000000            145.000000
mean            0.000078             0.019467             72.000000
std             0.000117             0.029967             42.001943
min             0.000000             0.000085              0.000000
25%             0.000017             0.005833             36.000000
50%             0.000039             0.012138             72.000000
75%             0.000088             0.023780            108.000000
max             0.000705             0.308121            144.000000

The output confirms that the KPI values are realistic, non-negative, and logically valid.

Validate Sample Countries Manually, This step displays a few sample countries to manually verify that the KPI values look correct and logical.

In [ ]:
print("\nSample Data:\n")
print(df[[
    "country",
    "assets_per_capita",
    "budget_to_gdp_ratio",
    "power_index_rank_gap"
]].head(5))

Sample Data:

       country  assets_per_capita  budget_to_gdp_ratio  power_index_rank_gap
0  Afghanistan       3.195418e-07             0.001763                 135.0
1      Albania       3.481165e-05             0.014019                 106.0
2      Algeria       9.818001e-05             0.034582                  22.0
3       Angola       8.453833e-05             0.112134                  19.0
4    Argentina       3.119328e-05             0.000819                  96.0

The sample output confirms that the KPI values are properly calculated and aligned with their respective countries.

This step checks for infinite values in numeric columns to ensure no division-by-zero errors occurred during KPI calculations.

In [ ]:
import numpy as np

print("Infinite values:\n",
      np.isinf(df.select_dtypes(include=[float, int])).sum())

Infinite values:
 active_personnel                             0
aircraft_carriers                            0
armored_fighting_vehicles                    0
attack_aircraft                              0
attack_helicopters                           0
border_coverage_km                           0
coal_consumption_mt                          0
coal_production_cum                          0
coastal_patrol_craft                         0
coastline_coverage_km                        0
corvettes                                    0
defense_budget_usd                           0
destroyers                                   0
external_debt_usd                            0
fighter_aircraft                             0
fit_for_service                              0
foreign_exchange_and_gold_reserves_usd       0
frigates                                     0
helicopter_carriers                          0
labour_force                                 0
major_ports_and_terminals                    0
mine_warfare_craft                           0
natural_gas_consumption_cum                  0
natural_gas_production_cum                   0
oil_consumption_bbl                          0
oil_production_bbl                           0
paramilitary                                 0
population_reaching_military_age_annually    0
proven_coal_reserves_cum                     0
proven_natural_gas_reserves_cum              0
proven_oil_reserves_bbl                      0
purchasing_power_parity_usd                  0
railway_coverage_km                          0
reserve_personnel                            0
roadway_coverage_km                          0
rocket_projectors                            0
self_propelled_artillery                     0
special_mission_aircraft                     0
submarines                                   0
tanker_aircraft                              0
tanks                                        0
total_land_area_sq_km                        0
total_merchant_marine_fleet                  0
total_military_aircraft                      0
total_military_helicopters                   0
total_military_manpower                      0
total_naval_fleet                            0
total_naval_fleet_tonnage_mt                 0
total_population                             0
total_serviceable_airports                   0
towed_artillery                              0
trainer_aircraft                             0
transport_aircraft                           0
waterway_coverage_km                         0
assets_per_capita                            0
budget_to_gdp_ratio                          0
rank                                         0
power_index_rank_gap                         0
dtype: int64

The output confirms that there are no infinite values in the dataset, indicating that all KPI calculations are numerically stable and valid.

Export Final KPI: This step exports the final dataset containing all engineered KPIs into a CSV file for dashboard integration and further analysis.

In [ ]:
df.to_csv("military_final.csv", index=False)

In [ ]:
import pandas as pd

df = pd.read_csv("military_final.csv")
df.head()

,country,active_personnel,aircraft_carriers,armored_fighting_vehicles,attack_aircraft,attack_helicopters,border_coverage_km,coal_consumption_mt,coal_production_cum,coastal_patrol_craft,...,total_serviceable_airports,towed_artillery,trainer_aircraft,transport_aircraft,waterway_coverage_km,assets_per_capita,budget_to_gdp_ratio,rank,power_index_rank_gap,strength_category
0,Afghanistan,75000.0,0.0,3902.0,0.0,0.0,5987.0,503000.0,767000.0,0.0,...,68.0,0.0,0.0,2.0,1200.0,3.195418e-07,0.001763,136.0,135.0,Low
1,Albania,7500.0,0.0,1492.0,0.0,0.0,691.0,255000.0,473000.0,33.0,...,3.0,0.0,0.0,1.0,41.0,3.481165e-05,0.014019,107.0,106.0,Low
2,Algeria,130000.0,0.0,24920.0,42.0,74.0,6734.0,3000.0,0.0,75.0,...,95.0,483.0,90.0,63.0,0.0,9.818001e-05,0.034582,23.0,22.0,Low
3,Angola,107000.0,0.0,2258.0,6.0,14.0,5369.0,0.0,0.0,32.0,...,107.0,575.0,56.0,32.0,1300.0,8.453833e-05,0.112134,20.0,19.0,Low
4,Argentina,108000.0,0.0,22432.0,11.0,0.0,11968.0,2534000.0,869000.0,13.0,...,764.0,172.0,71.0,25.0,11000.0,3.119328e-05,0.000819,97.0,96.0,Low

In [ ]:
df.dtypes

country                                       object
active_personnel                             float64
aircraft_carriers                            float64
armored_fighting_vehicles                    float64
attack_aircraft                              float64
attack_helicopters                           float64
border_coverage_km                           float64
coal_consumption_mt                          float64
coal_production_cum                          float64
coastal_patrol_craft                         float64
coastline_coverage_km                        float64
corvettes                                    float64
defense_budget_usd                           float64
destroyers                                   float64
external_debt_usd                            float64
fighter_aircraft                             float64
fit_for_service                              float64
foreign_exchange_and_gold_reserves_usd       float64
frigates                                     float64
helicopter_carriers                          float64
labour_force                                 float64
major_ports_and_terminals                    float64
mine_warfare_craft                           float64
natural_gas_consumption_cum                  float64
natural_gas_production_cum                   float64
oil_consumption_bbl                          float64
oil_production_bbl                           float64
paramilitary                                 float64
population_reaching_military_age_annually    float64
proven_coal_reserves_cum                     float64
proven_natural_gas_reserves_cum              float64
proven_oil_reserves_bbl                      float64
purchasing_power_parity_usd                  float64
railway_coverage_km                          float64
reserve_personnel                            float64
roadway_coverage_km                          float64
rocket_projectors                            float64
self_propelled_artillery                     float64
special_mission_aircraft                     float64
submarines                                   float64
tanker_aircraft                              float64
tanks                                        float64
total_land_area_sq_km                        float64
total_merchant_marine_fleet                  float64
total_military_aircraft                      float64
total_military_helicopters                   float64
total_military_manpower                      float64
total_naval_fleet                            float64
total_naval_fleet_tonnage_mt                 float64
total_population                             float64
total_serviceable_airports                   float64
towed_artillery                              float64
trainer_aircraft                             float64
transport_aircraft                           float64
waterway_coverage_km                         float64
assets_per_capita                            float64
budget_to_gdp_ratio                          float64
rank                                         float64
power_index_rank_gap                         float64
strength_category                             object
dtype: object

The final KPI-enhanced dataset was successfully saved as military_final.csv and is ready for visualization and reporting.