#Module-2 Data Cleaning & Standardization

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Military_raw_data (6).csv to Military_raw_data (6).csv

# 🌍 Step 1 – Load Raw Military Data
**Military Dataset Inspection**

This step loads the raw military dataset and inspects its structure, column names, data types, and sample rows.  
*Purpose:* Identify initial data quality and columns needing cleaning.

In [4]:

import pandas as pd

df = pd.read_csv("Military_raw_data (6).csv")
print(df.head())
print(df.info())

                               country  power_index_rank  power_index_score  \
0  2026United States Military Strength                 1             0.0741
1         2026Russia Military Strength                 2             0.0791
2          2026China Military Strength                 3             0.0919
3          2026India Military Strength                 4             0.1346
4    2026South Korea Military Strength                 5             0.1642

   purchasing_power_parity  foreign_exchange/gold  defense_budget  \
0                        2                      3               1
1                        4                      6               3
2                        1                      1               2
3                        3                      5               5
4                       14                     10              15

   external_debt  square_land_area  coastline_coverage  shared_borders  ...  \
0            145                 3                 100             127  ...
1            112                 1                 105             131  ...
2            121                 4                  98             132  ...
3            110                 7                  91             129  ...
4            123               104                  65               4  ...

   coal_consumption     coal_deficit  coal_proven_reserves  internet_coverage  \
0               117   +39,078,000 mt                     1                  8
1               116  +240,367,000 mt                     2                  9
2               119  -386,000,000 mt                     3                 22
3               118  -242,000,000 mt                     5                 37
4               111  -120,736,000 mt                    56                  4

   labor_force merchant_marine_fleet  ports_/_trade_terminals  airports  \
0            3                     6                        1         1
1            9                     8                       10         8
2            1                     2                       11        15
3            2                    12                       13        22
4           23                    10                       32        51

   roadway_coverage  railway_coverage
0                 1                 1
1                 5                 3
2                 3                 2
3                 2                 4
4                50                48

[5 rows x 66 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 66 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   country                        145 non-null    object
 1   power_index_rank               145 non-null    int64
 2   power_index_score              145 non-null    float64
 3   purchasing_power_parity        145 non-null    int64
 4   foreign_exchange/gold          145 non-null    int64
 5   defense_budget                 145 non-null    int64
 6   external_debt                  145 non-null    int64
 7   square_land_area               145 non-null    int64
 8   coastline_coverage             145 non-null    int64
 9   shared_borders                 145 non-null    int64
 10  waterways_(usable)             145 non-null    int64
 11  total_population               145 non-null    int64
 12  available_manpower             145 non-null    int64
 13  fit-for-service                145 non-null    int64
 14  reaching_mil_age_annually      145 non-null    int64
 15  tot_mil._personnel_(est.)      145 non-null    object
 16  active_personnel               145 non-null    int64
 17  reserve_personnel              145 non-null    int64
 18  paramilitary                   145 non-null    int64
 19  air_force_personnel*           145 non-null    int64
 20  army_personnel*                145 non-null    int64
 21  navy_personnel*                145 non-null    int64
 22  yearly_mobilization_potential  145 non-null    object
 23  aircraft_total                 145 non-null    int64
 24  fighters                       145 non-null    int64
 25  attack_types                   145 non-null    int64
 26  transports_(fixed-wing)        145 non-null    int64
 27  trainers                       145 non-null    int64
 28  special-mission                145 non-null    int64
 29  tanker_fleet                   145 non-null    int64
 30  helicopters                    145 non-null    int64
 31  attack_helicopters             145 non-null    int64
 32  tanks                          145 non-null    int64
 33  vehicles                       145 non-null    int64
 34  self-propelled_artillery       145 non-null    int64
 35  towed_artillery                145 non-null    int64
 36  mlrs_(rocket_artillery)        145 non-null    int64
 37  total_assets                   113 non-null    float64
 38  total_tonnage                  51 non-null     float64
 39  aircraft_carriers              113 non-null    float64
 40  helicopter_carriers            113 non-null    float64
 41  destroyers                     113 non-null    float64
 42  frigates                       113 non-null    float64
 43  corvettes                      113 non-null    float64
 44  submarines                     113 non-null    float64
 45  patrol_vessels                 113 non-null    float64
 46  mine_warfare                   113 non-null    float64
 47  oil_production                 145 non-null    int64
 48  oil_consumption                145 non-null    int64
 49  oil_deficit                    145 non-null    object
 50  oil_proven_reserves            145 non-null    int64
 51  natural_gas_production         145 non-null    int64
 52  natural_gas_consumption        145 non-null    int64
 53  natural_gas_deficit            145 non-null    object
 54  nat.gas_proven_rez             145 non-null    int64
 55  coal_production                145 non-null    int64
 56  coal_consumption               145 non-null    int64
 57  coal_deficit                   145 non-null    object
 58  coal_proven_reserves           145 non-null    int64
 59  internet_coverage              145 non-null    int64
 60  labor_force                    145 non-null    int64
 61  merchant_marine_fleet          145 non-null    int64
 62  ports_/_trade_terminals        145 non-null    int64
 63  airports                       145 non-null    int64
 64  roadway_coverage               145 non-null    int64
 65  railway_coverage               145 non-null    int64
dtypes: float64(11), int64(49), object(6)
memory usage: 74.9+ KB
None

# 🔍 Step 2 – Identify Data Noise
**Check for Inconsistencies**

Review all column names and detect noisy numeric fields (text, commas, units, symbols).  
*Purpose:* Ensure numeric columns are ready for processing.

In [5]:

print(df.columns.tolist())
print(df.info())

['country', 'power_index_rank', 'power_index_score', 'purchasing_power_parity', 'foreign_exchange/gold', 'defense_budget', 'external_debt', 'square_land_area', 'coastline_coverage', 'shared_borders', 'waterways_(usable)', 'total_population', 'available_manpower', 'fit-for-service', 'reaching_mil_age_annually', 'tot_mil._personnel_(est.)', 'active_personnel', 'reserve_personnel', 'paramilitary', 'air_force_personnel*', 'army_personnel*', 'navy_personnel*', 'yearly_mobilization_potential', 'aircraft_total', 'fighters', 'attack_types', 'transports_(fixed-wing)', 'trainers', 'special-mission', 'tanker_fleet', 'helicopters', 'attack_helicopters', 'tanks', 'vehicles', 'self-propelled_artillery', 'towed_artillery', 'mlrs_(rocket_artillery)', 'total_assets', 'total_tonnage', 'aircraft_carriers', 'helicopter_carriers', 'destroyers', 'frigates', 'corvettes', 'submarines', 'patrol_vessels', 'mine_warfare', 'oil_production', 'oil_consumption', 'oil_deficit', 'oil_proven_reserves', 'natural_gas_production', 'natural_gas_consumption', 'natural_gas_deficit', 'nat.gas_proven_rez', 'coal_production', 'coal_consumption', 'coal_deficit', 'coal_proven_reserves', 'internet_coverage', 'labor_force', 'merchant_marine_fleet', 'ports_/_trade_terminals', 'airports', 'roadway_coverage', 'railway_coverage']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 66 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   country                        145 non-null    object
 1   power_index_rank               145 non-null    int64
 2   power_index_score              145 non-null    float64
 3   purchasing_power_parity        145 non-null    int64
 4   foreign_exchange/gold          145 non-null    int64
 5   defense_budget                 145 non-null    int64
 6   external_debt                  145 non-null    int64
 7   square_land_area               145 non-null    int64
 8   coastline_coverage             145 non-null    int64
 9   shared_borders                 145 non-null    int64
 10  waterways_(usable)             145 non-null    int64
 11  total_population               145 non-null    int64
 12  available_manpower             145 non-null    int64
 13  fit-for-service                145 non-null    int64
 14  reaching_mil_age_annually      145 non-null    int64
 15  tot_mil._personnel_(est.)      145 non-null    object
 16  active_personnel               145 non-null    int64
 17  reserve_personnel              145 non-null    int64
 18  paramilitary                   145 non-null    int64
 19  air_force_personnel*           145 non-null    int64
 20  army_personnel*                145 non-null    int64
 21  navy_personnel*                145 non-null    int64
 22  yearly_mobilization_potential  145 non-null    object
 23  aircraft_total                 145 non-null    int64
 24  fighters                       145 non-null    int64
 25  attack_types                   145 non-null    int64
 26  transports_(fixed-wing)        145 non-null    int64
 27  trainers                       145 non-null    int64
 28  special-mission                145 non-null    int64
 29  tanker_fleet                   145 non-null    int64
 30  helicopters                    145 non-null    int64
 31  attack_helicopters             145 non-null    int64
 32  tanks                          145 non-null    int64
 33  vehicles                       145 non-null    int64
 34  self-propelled_artillery       145 non-null    int64
 35  towed_artillery                145 non-null    int64
 36  mlrs_(rocket_artillery)        145 non-null    int64
 37  total_assets                   113 non-null    float64
 38  total_tonnage                  51 non-null     float64
 39  aircraft_carriers              113 non-null    float64
 40  helicopter_carriers            113 non-null    float64
 41  destroyers                     113 non-null    float64
 42  frigates                       113 non-null    float64
 43  corvettes                      113 non-null    float64
 44  submarines                     113 non-null    float64
 45  patrol_vessels                 113 non-null    float64
 46  mine_warfare                   113 non-null    float64
 47  oil_production                 145 non-null    int64
 48  oil_consumption                145 non-null    int64
 49  oil_deficit                    145 non-null    object
 50  oil_proven_reserves            145 non-null    int64
 51  natural_gas_production         145 non-null    int64
 52  natural_gas_consumption        145 non-null    int64
 53  natural_gas_deficit            145 non-null    object
 54  nat.gas_proven_rez             145 non-null    int64
 55  coal_production                145 non-null    int64
 56  coal_consumption               145 non-null    int64
 57  coal_deficit                   145 non-null    object
 58  coal_proven_reserves           145 non-null    int64
 59  internet_coverage              145 non-null    int64
 60  labor_force                    145 non-null    int64
 61  merchant_marine_fleet          145 non-null    int64
 62  ports_/_trade_terminals        145 non-null    int64
 63  airports                       145 non-null    int64
 64  roadway_coverage               145 non-null    int64
 65  railway_coverage               145 non-null    int64
dtypes: float64(11), int64(49), object(6)
memory usage: 74.9+ KB
None

# 🧹 Step 3 – Clean Numeric Columns
**Transform Text to Numbers**

Remove non-numeric characters and convert columns to float.  
*Purpose:* Enable calculations and KPI engineering without errors.

In [6]:

def clean_numeric(col):
    return (
        col.astype(str)
           .str.replace(r'[^0-9.]', '', regex=True)
           .replace('', '0')
           .astype(float)
    )

for col in df.columns:
    if col != 'country':  # Exclude country names
        df[col] = clean_numeric(df[col])

# ✨ Step 4 – Standardize Column Names
**Consistency Across Columns**

Strip extra spaces and convert all column names to lowercase.  
*Purpose:* Avoid issues during coding and analysis.

In [7]:

df.columns = df.columns.str.strip().str.lower()

# 💧 Step 5 – Handle Missing Values
**Fill Gaps**

Replace missing values with zero.  
*Purpose:* Prevent calculation errors in subsequent KPI computations.

In [8]:

df = df.fillna(0)

# ✅ Step 6 – Validate Cleaned Data
**Data Integrity Checks**

Check data types, missing values, duplicates, and basic statistics.  
*Purpose:* Ensure dataset is clean and reliable for analysis.

In [9]:

df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 66 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   country                        145 non-null    object
 1   power_index_rank               145 non-null    float64
 2   power_index_score              145 non-null    float64
 3   purchasing_power_parity        145 non-null    float64
 4   foreign_exchange/gold          145 non-null    float64
 5   defense_budget                 145 non-null    float64
 6   external_debt                  145 non-null    float64
 7   square_land_area               145 non-null    float64
 8   coastline_coverage             145 non-null    float64
 9   shared_borders                 145 non-null    float64
 10  waterways_(usable)             145 non-null    float64
 11  total_population               145 non-null    float64
 12  available_manpower             145 non-null    float64
 13  fit-for-service                145 non-null    float64
 14  reaching_mil_age_annually      145 non-null    float64
 15  tot_mil._personnel_(est.)      145 non-null    float64
 16  active_personnel               145 non-null    float64
 17  reserve_personnel              145 non-null    float64
 18  paramilitary                   145 non-null    float64
 19  air_force_personnel*           145 non-null    float64
 20  army_personnel*                145 non-null    float64
 21  navy_personnel*                145 non-null    float64
 22  yearly_mobilization_potential  145 non-null    float64
 23  aircraft_total                 145 non-null    float64
 24  fighters                       145 non-null    float64
 25  attack_types                   145 non-null    float64
 26  transports_(fixed-wing)        145 non-null    float64
 27  trainers                       145 non-null    float64
 28  special-mission                145 non-null    float64
 29  tanker_fleet                   145 non-null    float64
 30  helicopters                    145 non-null    float64
 31  attack_helicopters             145 non-null    float64
 32  tanks                          145 non-null    float64
 33  vehicles                       145 non-null    float64
 34  self-propelled_artillery       145 non-null    float64
 35  towed_artillery                145 non-null    float64
 36  mlrs_(rocket_artillery)        145 non-null    float64
 37  total_assets                   145 non-null    float64
 38  total_tonnage                  145 non-null    float64
 39  aircraft_carriers              145 non-null    float64
 40  helicopter_carriers            145 non-null    float64
 41  destroyers                     145 non-null    float64
 42  frigates                       145 non-null    float64
 43  corvettes                      145 non-null    float64
 44  submarines                     145 non-null    float64
 45  patrol_vessels                 145 non-null    float64
 46  mine_warfare                   145 non-null    float64
 47  oil_production                 145 non-null    float64
 48  oil_consumption                145 non-null    float64
 49  oil_deficit                    145 non-null    float64
 50  oil_proven_reserves            145 non-null    float64
 51  natural_gas_production         145 non-null    float64
 52  natural_gas_consumption        145 non-null    float64
 53  natural_gas_deficit            145 non-null    float64
 54  nat.gas_proven_rez             145 non-null    float64
 55  coal_production                145 non-null    float64
 56  coal_consumption               145 non-null    float64
 57  coal_deficit                   145 non-null    float64
 58  coal_proven_reserves           145 non-null    float64
 59  internet_coverage              145 non-null    float64
 60  labor_force                    145 non-null    float64
 61  merchant_marine_fleet          145 non-null    float64
 62  ports_/_trade_terminals        145 non-null    float64
 63  airports                       145 non-null    float64
 64  roadway_coverage               145 non-null    float64
 65  railway_coverage               145 non-null    float64
dtypes: float64(65), object(1)
memory usage: 74.9+ KB

np.int64(0)

# 💾 Step 7 – Export Cleaned Dataset
**Save for Dashboard Integration**

Export cleaned dataset to a CSV file.  
*Purpose:* Ready the dataset for KPI engineering and reporting.

In [10]:

df.to_csv("military_data_cleaned.csv", index=False)

In [11]:
print(df.isnull().sum())
print(df.dtypes)
print(df.duplicated().sum())

country                    0
power_index_rank           0
power_index_score          0
purchasing_power_parity    0
foreign_exchange/gold      0
                          ..
merchant_marine_fleet      0
ports_/_trade_terminals    0
airports                   0
roadway_coverage           0
railway_coverage           0
Length: 66, dtype: int64
country                     object
power_index_rank           float64
power_index_score          float64
purchasing_power_parity    float64
foreign_exchange/gold      float64
                            ...
merchant_marine_fleet      float64
ports_/_trade_terminals    float64
airports                   float64
roadway_coverage           float64
railway_coverage           float64
Length: 66, dtype: object
0

##Module-3 KPI Engineering & Feature Creation

# 📊 Step 8 – Load Clean Dataset
**Ready for KPI Engineering**

Load the cleaned dataset to compute derived metrics and KPIs.  
*Purpose:* Prepare data for analysis and visualization.

In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv("military_data_cleaned.csv")
print(df.head())

                               country  power_index_rank  power_index_score  \
0  2026United States Military Strength               1.0             0.0741
1         2026Russia Military Strength               2.0             0.0791
2          2026China Military Strength               3.0             0.0919
3          2026India Military Strength               4.0             0.1346
4    2026South Korea Military Strength               5.0             0.1642

   purchasing_power_parity  foreign_exchange/gold  defense_budget  \
0                      2.0                    3.0             1.0
1                      4.0                    6.0             3.0
2                      1.0                    1.0             2.0
3                      3.0                    5.0             5.0
4                     14.0                   10.0            15.0

   external_debt  square_land_area  coastline_coverage  shared_borders  ...  \
0          145.0               3.0               100.0           127.0  ...
1          112.0               1.0               105.0           131.0  ...
2          121.0               4.0                98.0           132.0  ...
3          110.0               7.0                91.0           129.0  ...
4          123.0             104.0                65.0             4.0  ...

   coal_consumption  coal_deficit  coal_proven_reserves  internet_coverage  \
0             117.0    39078000.0                   1.0                8.0
1             116.0   240367000.0                   2.0                9.0
2             119.0   386000000.0                   3.0               22.0
3             118.0   242000000.0                   5.0               37.0
4             111.0   120736000.0                  56.0                4.0

   labor_force  merchant_marine_fleet  ports_/_trade_terminals  airports  \
0          3.0                    6.0                      1.0       1.0
1          9.0                    8.0                     10.0       8.0
2          1.0                    2.0                     11.0      15.0
3          2.0                   12.0                     13.0      22.0
4         23.0                   10.0                     32.0      51.0

   roadway_coverage  railway_coverage
0               1.0               1.0
1               5.0               3.0
2               3.0               2.0
3               2.0               4.0
4              50.0              48.0

[5 rows x 66 columns]

# ⚡ Step 9a – Assets per Capita
**Measure Equipment Strength**

Compute total military assets per soldier.  
*Purpose:* Compare equipment strength across countries.

In [17]:

import numpy as np

df["assets_per_capita"] = (
    df["aircraft_total"] +
    df["tanks"] +
    df["submarines"]
) / df["available_manpower"].replace(0, np.nan)

# 💰 Step 9b – Budget-to-GDP Ratio
**Economic Investment in Defense**

Calculate defense spending relative to national GDP (PPP-adjusted).  
*Purpose:* Assess defense investment intensity.

In [20]:

df["budget_to_gdp_ratio"] = (
    df["defense_budget"] /
    df["purchasing_power_parity"].replace(0, np.nan)
)

# 🏆 Step 9c – Power Index Rank Gap
**Compare Relative Ranking**

Rank countries by defense budget and compute the gap from the top-ranked nation.  
*Purpose:* Facilitate comparative analysis.

In [22]:

df["rank"] = df["defense_budget"].rank(ascending=False)
top_rank = df["rank"].min()
df["power_index_rank_gap"] = df["rank"] - top_rank

# 🛡 Step 10 – Strength Category
**Classify Military Capability**

Categorize countries into Low, Medium, High tiers using assets per capita.  
*Purpose:* Provide a simple visual indicator of military strength.

In [23]:

df["strength_category"] = pd.cut(
    df["assets_per_capita"],
    bins=3,
    labels=["Low", "Medium", "High"]
)

# 🔍 Step 11 – Validate KPI Calculations
**Check for Errors**

Inspect for infinite or unrealistic values, and verify a sample of countries.  
*Purpose:* Ensure KPIs are logical and accurate.

In [24]:

print("Infinite values check:\n")
print(np.isinf(df.select_dtypes(include=[float, int])).sum())

print("\nKPI Statistics:\n")
print(df[["assets_per_capita", "budget_to_gdp_ratio", "power_index_rank_gap"]].describe())

print("\nSample Data:\n")
print(df[["country", "assets_per_capita", "budget_to_gdp_ratio", "power_index_rank_gap"]].head(5))

Infinite values check:

power_index_rank           0
power_index_score          0
purchasing_power_parity    0
foreign_exchange/gold      0
defense_budget             0
                          ..
railway_coverage           0
assets_per_capita          0
budget_to_gdp_ratio        0
rank                       0
power_index_rank_gap       0
Length: 69, dtype: int64

KPI Statistics:

       assets_per_capita  budget_to_gdp_ratio  power_index_rank_gap
count         145.000000           145.000000            145.000000
mean            4.398827             1.110898             72.000000
std             5.820839             0.587346             42.001984
min             0.333333             0.304348              0.000000
25%             2.000000             0.777778             36.000000
50%             2.877698             0.979167             72.000000
75%             4.188235             1.226190            108.000000
max            48.200000             4.125000            144.000000

Sample Data:

                               country  assets_per_capita  \
0  2026United States Military Strength           2.000000
1         2026Russia Military Strength           0.555556
2          2026China Military Strength           6.000000
3          2026India Military Strength           8.000000
4    2026South Korea Military Strength           0.814815

   budget_to_gdp_ratio  power_index_rank_gap
0             0.500000                 144.0
1             0.750000                 142.0
2             2.000000                 143.0
3             1.666667                 140.0
4             1.071429                 130.0

# 📁 Step 12 – Export Final KPI Dataset
**Final Dataset for Analysis**

Save the dataset with all engineered KPIs for dashboards, reporting, and visualization.  
*Purpose:* Make the dataset ready for integration into analytics workflows.

In [25]:

df.to_csv("military_final.csv", index=False)

In [26]:
import pandas as pd

df = pd.read_csv("military_final.csv")
df.head()

,country,power_index_rank,power_index_score,purchasing_power_parity,foreign_exchange/gold,defense_budget,external_debt,square_land_area,coastline_coverage,shared_borders,...,merchant_marine_fleet,ports_/_trade_terminals,airports,roadway_coverage,railway_coverage,assets_per_capita,budget_to_gdp_ratio,rank,power_index_rank_gap,strength_category
0,2026United States Military Strength,1.0,0.0741,2.0,3.0,1.0,145.0,3.0,100.0,127.0,...,6.0,1.0,1.0,1.0,1.0,2.000000,0.500000,145.0,144.0,Low
1,2026Russia Military Strength,2.0,0.0791,4.0,6.0,3.0,112.0,1.0,105.0,131.0,...,8.0,10.0,8.0,5.0,3.0,0.555556,0.750000,143.0,142.0,Low
2,2026China Military Strength,3.0,0.0919,1.0,1.0,2.0,121.0,4.0,98.0,132.0,...,2.0,11.0,15.0,3.0,2.0,6.000000,2.000000,144.0,143.0,Low
3,2026India Military Strength,4.0,0.1346,3.0,5.0,5.0,110.0,7.0,91.0,129.0,...,12.0,13.0,22.0,2.0,4.0,8.000000,1.666667,141.0,140.0,Low
4,2026South Korea Military Strength,5.0,0.1642,14.0,10.0,15.0,123.0,104.0,65.0,4.0,...,10.0,32.0,51.0,50.0,48.0,0.814815,1.071429,131.0,130.0,Low

In [27]:

df.dtypes

country                     object
power_index_rank           float64
power_index_score          float64
purchasing_power_parity    float64
foreign_exchange/gold      float64
                            ...
assets_per_capita          float64
budget_to_gdp_ratio        float64
rank                       float64
power_index_rank_gap       float64
strength_category           object
Length: 71, dtype: object

In [29]:
from google.colab import files
import pandas as pd

# Example: Save cleaned dataframe
df.to_csv("military_data_cleaned.csv", index=False)

# Download to local machine
files.download("military_data_cleaned.csv")

The final KPI-enhanced dataset was successfully saved as military_final.csv and is ready for visualization and reporting.