Task6: Data Cleaning & Standardization

In [6]:
import pandas as pd

df = pd.read_csv('/content/Military_raw_data.csv')
print("Data loaded successfully into a DataFrame named 'df'.")
df

Data loaded successfully into a DataFrame named 'df'.

,Country_Code,Country_Name,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,...,natural_gas_production_cum,natural_gas_consumption_cum,proven_natural_gas_reserves_cum,coal_production_cum,coal_consumption_mt,proven_coal_reserves_cum,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km
0,USA,United States,"341,963,408","150,463,900","124,816,644","4,445,524","1,333,030","799,500",0,"13,032",...,"1,029,000,000,000 \t\t\...","914,301,000,000 \t\t\t\...","13,402,000,000,000 \t\t...","534,234,000 \t\t\t\t\t\...","495,156,000 \t\t\t\t\t\...","247,883,000,000 \t\t\t\...","9,833,517 \t\t\t\t\t\t\...","19,924 \t\t\t\t\t\t\r\n...","12,002 \t\t\t\t\t\t\r\n...","41,009 \t\t\t\t\t\t\r\n..."
1,RUS,Russia,"140,820,810","69,002,197","46,189,226","1,267,387","1,320,000","2,000,000","250,000","4,237",...,"617,830,000,000 \t\t\t\...","472,239,000,000 \t\t\t\...","47,805,000,000,000 \t\t...","531,130,000 \t\t\t\t\t\...","290,763,000 \t\t\t\t\t\...","162,166,000,000 \t\t\t\...","17,098,242 \t\t\t\t\t\t...","37,653 \t\t\t\t\t\t\r\n...","22,407 \t\t\t\t\t\t\r\n...","102,000 \t\t\t\t\t\t\r\..."
2,CHN,China,"1,415,043,270","764,123,366","626,864,169","19,810,606","2,035,000","510,000","625,000","3,529",...,"225,341,000,000 \t\t\t\...","366,160,000,000 \t\t\t\...","6,654,000,000,000 \t\t\...","4,805,000,000 \t\t\t\t\...","5,191,000,000 \t\t\t\t\...","157,041,000,000 \t\t\t\...","9,596,960 \t\t\t\t\t\t\...","14,500 \t\t\t\t\t\t\r\n...","22,457 \t\t\t\t\t\t\r\n...","27,700 \t\t\t\t\t\t\r\n..."
3,IND,India,"1,409,128,296","662,290,299","522,786,598","23,955,181","1,431,000","1,000,000","2,527,000","2,183",...,"33,170,000,000 \t\t\t\t...","58,867,000,000 \t\t\t\t...","1,381,000,000,000 \t\t\...","1,020,000,000 \t\t\t\t\...","1,262,000,000 \t\t\t\t\...","127,727,000,000 \t\t\t\...","3,287,263 \t\t\t\t\t\t\...","7,000 \t\t\t\t\t\t\r\n\...","13,888 \t\t\t\t\t\t\r\n...","14,500 \t\t\t\t\t\t\r\n..."
4,SKO,South Korea,"52,081,799","26,040,900","21,353,538","416,654","450,000","3,100,000","120,000","1,540",...,"55,127,000 \t\t\t\t\t\t...","59,480,000,000 \t\t\t\t...","7,079,000,000 \t\t\t\t\...","16,081,000 \t\t\t\t\t\t...","136,817,000 \t\t\t\t\t\...","326,000,000 \t\t\t\t\t\...","99,720 \t\t\t\t\t\t\r\n...","2,413 \t\t\t\t\t\t\r\n\...",237 \t\t\t\t\t\t\r\n\t\...,"1,600 \t\t\t\t\t\t\r\n\..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,LIB,Liberia,"5,437,249","2,392,390","1,913,912","65,247","2,100",0,"5,500",0,...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"111,369 \t\t\t\t\t\t\r\...",579 \t\t\t\t\t\t\r\n\t\...,"1,667 \t\t\t\t\t\t\r\n\...",0 \t\t\t\t\t\t\r\n\t\t\...
141,SRN,Suriname,"646,758","142,287","84,079","3,234","2,500",0,200,3,...,"7,109,000 \t\t\t\t\t\t\...","6,967,000 \t\t\t\t\t\t\...",0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"163,820 \t\t\t\t\t\t\r\...",386 \t\t\t\t\t\t\r\n\t\...,"1,907 \t\t\t\t\t\t\r\n\...","1,200 \t\t\t\t\t\t\r\n\..."
142,CAR,Central African Republic,"5,650,957","2,203,873","1,254,512","101,717","30,000",0,"1,000",8,...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"3,000,000 \t\t\t\t\t\t\...","622,984 \t\t\t\t\t\t\r\...",0 \t\t\t\t\t\t\r\n\t\t\...,"5,920 \t\t\t\t\t\t\r\n\...","2,800 \t\t\t\t\t\t\r\n\..."
143,BLZ,Beliz,"415,789","158,000","90,226","8,732","2,000",850,0,3,...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"22,966 \t\t\t\t\t\t\r\n...",386 \t\t\t\t\t\t\r\n\t\...,542 \t\t\t\t\t\t\r\n\t\...,825 \t\t\t\t\t\t\r\n\t\...
144,BUT,Bhutan,"884,546","203,446","122,067","4,423","16,000","50,000",0,2,...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"4,000 \t\t\t\t\t\t\r\n\...","105,000 \t\t\t\t\t\t\r\...",0 \t\t\t\t\t\t\r\n\t\t\...,"38,394 \t\t\t\t\t\t\r\n...",0 \t\t\t\t\t\t\r\n\t\t\...,"1,136 \t\t\t\t\t\t\r\n\...",0 \t\t\t\t\t\t\r\n\t\t\...

In [7]:
#duplicate
# df2 = pd.concat([df, df], ignore_index=True)

# print(df2)
df.drop_duplicates()

,Country_Code,Country_Name,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,...,natural_gas_production_cum,natural_gas_consumption_cum,proven_natural_gas_reserves_cum,coal_production_cum,coal_consumption_mt,proven_coal_reserves_cum,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km
0,USA,United States,"341,963,408","150,463,900","124,816,644","4,445,524","1,333,030","799,500",0,"13,032",...,"1,029,000,000,000 \t\t\...","914,301,000,000 \t\t\t\...","13,402,000,000,000 \t\t...","534,234,000 \t\t\t\t\t\...","495,156,000 \t\t\t\t\t\...","247,883,000,000 \t\t\t\...","9,833,517 \t\t\t\t\t\t\...","19,924 \t\t\t\t\t\t\r\n...","12,002 \t\t\t\t\t\t\r\n...","41,009 \t\t\t\t\t\t\r\n..."
1,RUS,Russia,"140,820,810","69,002,197","46,189,226","1,267,387","1,320,000","2,000,000","250,000","4,237",...,"617,830,000,000 \t\t\t\...","472,239,000,000 \t\t\t\...","47,805,000,000,000 \t\t...","531,130,000 \t\t\t\t\t\...","290,763,000 \t\t\t\t\t\...","162,166,000,000 \t\t\t\...","17,098,242 \t\t\t\t\t\t...","37,653 \t\t\t\t\t\t\r\n...","22,407 \t\t\t\t\t\t\r\n...","102,000 \t\t\t\t\t\t\r\..."
2,CHN,China,"1,415,043,270","764,123,366","626,864,169","19,810,606","2,035,000","510,000","625,000","3,529",...,"225,341,000,000 \t\t\t\...","366,160,000,000 \t\t\t\...","6,654,000,000,000 \t\t\...","4,805,000,000 \t\t\t\t\...","5,191,000,000 \t\t\t\t\...","157,041,000,000 \t\t\t\...","9,596,960 \t\t\t\t\t\t\...","14,500 \t\t\t\t\t\t\r\n...","22,457 \t\t\t\t\t\t\r\n...","27,700 \t\t\t\t\t\t\r\n..."
3,IND,India,"1,409,128,296","662,290,299","522,786,598","23,955,181","1,431,000","1,000,000","2,527,000","2,183",...,"33,170,000,000 \t\t\t\t...","58,867,000,000 \t\t\t\t...","1,381,000,000,000 \t\t\...","1,020,000,000 \t\t\t\t\...","1,262,000,000 \t\t\t\t\...","127,727,000,000 \t\t\t\...","3,287,263 \t\t\t\t\t\t\...","7,000 \t\t\t\t\t\t\r\n\...","13,888 \t\t\t\t\t\t\r\n...","14,500 \t\t\t\t\t\t\r\n..."
4,SKO,South Korea,"52,081,799","26,040,900","21,353,538","416,654","450,000","3,100,000","120,000","1,540",...,"55,127,000 \t\t\t\t\t\t...","59,480,000,000 \t\t\t\t...","7,079,000,000 \t\t\t\t\...","16,081,000 \t\t\t\t\t\t...","136,817,000 \t\t\t\t\t\...","326,000,000 \t\t\t\t\t\...","99,720 \t\t\t\t\t\t\r\n...","2,413 \t\t\t\t\t\t\r\n\...",237 \t\t\t\t\t\t\r\n\t\...,"1,600 \t\t\t\t\t\t\r\n\..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,LIB,Liberia,"5,437,249","2,392,390","1,913,912","65,247","2,100",0,"5,500",0,...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"111,369 \t\t\t\t\t\t\r\...",579 \t\t\t\t\t\t\r\n\t\...,"1,667 \t\t\t\t\t\t\r\n\...",0 \t\t\t\t\t\t\r\n\t\t\...
141,SRN,Suriname,"646,758","142,287","84,079","3,234","2,500",0,200,3,...,"7,109,000 \t\t\t\t\t\t\...","6,967,000 \t\t\t\t\t\t\...",0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"163,820 \t\t\t\t\t\t\r\...",386 \t\t\t\t\t\t\r\n\t\...,"1,907 \t\t\t\t\t\t\r\n\...","1,200 \t\t\t\t\t\t\r\n\..."
142,CAR,Central African Republic,"5,650,957","2,203,873","1,254,512","101,717","30,000",0,"1,000",8,...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"3,000,000 \t\t\t\t\t\t\...","622,984 \t\t\t\t\t\t\r\...",0 \t\t\t\t\t\t\r\n\t\t\...,"5,920 \t\t\t\t\t\t\r\n\...","2,800 \t\t\t\t\t\t\r\n\..."
143,BLZ,Beliz,"415,789","158,000","90,226","8,732","2,000",850,0,3,...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"22,966 \t\t\t\t\t\t\r\n...",386 \t\t\t\t\t\t\r\n\t\...,542 \t\t\t\t\t\t\r\n\t\...,825 \t\t\t\t\t\t\r\n\t\...
144,BUT,Bhutan,"884,546","203,446","122,067","4,423","16,000","50,000",0,2,...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,0 \t\t\t\t\t\t\r\n\t\t\...,"4,000 \t\t\t\t\t\t\r\n\...","105,000 \t\t\t\t\t\t\r\...",0 \t\t\t\t\t\t\r\n\t\t\...,"38,394 \t\t\t\t\t\t\r\n...",0 \t\t\t\t\t\t\r\n\t\t\...,"1,136 \t\t\t\t\t\t\r\n\...",0 \t\t\t\t\t\t\r\n\t\t\...

In [8]:
df.dtypes

Country_Code                                 object
Country_Name                                 object
total_population                             object
total_military_manpower                      object
fit_for_service                              object
population_reaching_military_age_annually    object
active_personnel                             object
reserve_personnel                            object
paramilitary                                 object
total_military_aircraft                      object
fighter_aircraft                             object
attack_aircraft                               int64
transport_aircraft                            int64
trainer_aircraft                             object
special_mission_aircraft                      int64
tanker_aircraft                               int64
total_military_helicopters                   object
attack_helicopters                           object
tanks                                        object
armored_fighting_vehicles                    object
self_propelled_artillery                     object
towed_artillery                              object
rocket_projectors                            object
total_naval_fleet                             int64
total_naval_fleet_tonnage_mt                 object
aircraft_carriers                             int64
helicopter_carriers                           int64
submarines                                    int64
destroyers                                    int64
frigates                                      int64
corvettes                                     int64
coastal_patrol_craft                          int64
mine_warfare_craft                            int64
defense_budget_usd                           object
external_debt_usd                            object
purchasing_power_parity_usd                  object
foreign_exchange_and_gold_reserves_usd       object
total_serviceable_airports                   object
labour_force                                 object
major_ports_and_terminals                     int64
total_merchant_marine_fleet                  object
railway_coverage_km                          object
roadway_coverage_km                          object
oil_production_bbl                           object
oil_consumption_bbl                          object
proven_oil_reserves_bbl                      object
natural_gas_production_cum                   object
natural_gas_consumption_cum                  object
proven_natural_gas_reserves_cum              object
coal_production_cum                          object
coal_consumption_mt                          object
proven_coal_reserves_cum                     object
total_land_area_sq_km                        object
coastline_coverage_km                        object
border_coverage_km                           object
waterway_coverage_km                         object
dtype: object

In [9]:
df['Country_Code']
df['Country_Name']
df['total_population']

import pandas as pd

def clean_numeric_column(df, column_name):
    df[column_name] = pd.to_numeric(
        df[column_name]
        .astype(str)                      # ensure string
        .str.replace(r'[^\d.]', '', regex=True),  # remove non-numeric chars
        errors='coerce'
    )
    return df

def clean_text_column(df, column_name):
    df[column_name] = pd.to_numeric(
        df[column_name]
        .astype(str)                              # ensure string
        .str.replace(r'[^\d.]', '', regex=True),  # keep only digits & decimal
        errors='coerce'
    )
    return df

df = clean_numeric_column(df, 'total_population')
df = clean_numeric_column(df, 'total_military_manpower')
df = clean_numeric_column(df, 'population_reaching_military_age_annually')
df = clean_numeric_column(df, 'active_personnel')
df = clean_numeric_column(df, 'reserve_personnel')
df = clean_numeric_column(df, 'paramilitary')
df = clean_numeric_column(df, 'total_military_aircraft')
df['total_military_aircraft']

df = clean_numeric_column(df, 'fighter_aircraft')
df['fighter_aircraft']

df = clean_numeric_column(df, 'attack_aircraft')
df['attack_aircraft']

df = clean_numeric_column(df, 'transport_aircraft')
df['transport_aircraft']

df = clean_numeric_column(df, 'trainer_aircraft')
df['trainer_aircraft']

df['special_mission_aircraft']
df['tanker_aircraft']


df = clean_numeric_column(df, 'attack_helicopters')
df['attack_helicopters']

df = clean_numeric_column(df, 'tanks')
df['tanks']

df = clean_numeric_column(df, 'armored_fighting_vehicles')
df['armored_fighting_vehicles']

df = clean_numeric_column(df, 'self_propelled_artillery')
df['self_propelled_artillery']

df = clean_numeric_column(df, 'towed_artillery')
df['towed_artillery']

df = clean_numeric_column(df, 'rocket_projectors')
df['rocket_projectors']

df = clean_numeric_column(df, 'total_naval_fleet')
df['total_naval_fleet']

df = clean_numeric_column(df, 'total_naval_fleet_tonnage_mt')
df['total_naval_fleet_tonnage_mt']

df[[
    'aircraft_carriers',
    'helicopter_carriers',
    'submarines',
    'destroyers',
    'frigates',
    'corvettes',
    'coastal_patrol_craft',
    'mine_warfare_craft'
]].dtypes


df = clean_text_column(df, 'defense_budget_usd')
df['defense_budget_usd']

df = clean_text_column(df, 'external_debt_usd')
df['external_debt_usd']

df = clean_text_column(df, 'purchasing_power_parity_usd')
df['purchasing_power_parity_usd']

df = clean_text_column(df, 'foreign_exchange_and_gold_reserves_usd')
df['foreign_exchange_and_gold_reserves_usd']

df = clean_numeric_column(df, 'total_serviceable_airports')
df['total_serviceable_airports']

df = clean_numeric_column(df, 'labour_force')
df['labour_force']

df = clean_numeric_column(df, 'major_ports_and_terminals')
df['major_ports_and_terminals']

df = clean_numeric_column(df, 'total_merchant_marine_fleet')
df['total_merchant_marine_fleet']

df = clean_numeric_column(df, 'railway_coverage_km')
df['railway_coverage_km']

df = clean_numeric_column(df, 'oil_production_bbl')
df['oil_production_bbl']

df = clean_numeric_column(df, 'oil_consumption_bbl')
df['oil_consumption_bbl']

df = clean_numeric_column(df, 'proven_oil_reserves_bbl')
df['proven_oil_reserves_bbl']

df = clean_numeric_column(df, 'natural_gas_production_cum')
df['natural_gas_production_cum']

df = clean_numeric_column(df, 'natural_gas_consumption_cum')
df['natural_gas_consumption_cum']

df = clean_numeric_column(df, 'proven_natural_gas_reserves_cum')
df['proven_natural_gas_reserves_cum']

df = clean_numeric_column(df, 'coal_production_cum')
df['coal_production_cum']

df = clean_numeric_column(df, 'coal_consumption_mt')
df['coal_consumption_mt']

df = clean_numeric_column(df, 'proven_coal_reserves_cum')
df['proven_coal_reserves_cum']

df = clean_numeric_column(df, 'total_land_area_sq_km')
df['total_land_area_sq_km']

df = clean_numeric_column(df, 'coastline_coverage_km')
df['coastline_coverage_km']

df = clean_numeric_column(df, 'border_coverage_km')
df['border_coverage_km']

df = clean_numeric_column(df, 'waterway_coverage_km')
df['waterway_coverage_km']

0       41009
1      102000
2       27700
3       14500
4        1600
        ...
140         0
141      1200
142      2800
143       825
144         0
Name: waterway_coverage_km, Length: 145, dtype: int64

In [10]:
df.dtypes

Country_Code                                  object
Country_Name                                  object
total_population                               int64
total_military_manpower                        int64
fit_for_service                               object
population_reaching_military_age_annually      int64
active_personnel                               int64
reserve_personnel                              int64
paramilitary                                   int64
total_military_aircraft                        int64
fighter_aircraft                               int64
attack_aircraft                                int64
transport_aircraft                             int64
trainer_aircraft                               int64
special_mission_aircraft                       int64
tanker_aircraft                                int64
total_military_helicopters                    object
attack_helicopters                             int64
tanks                                          int64
armored_fighting_vehicles                      int64
self_propelled_artillery                       int64
towed_artillery                                int64
rocket_projectors                              int64
total_naval_fleet                              int64
total_naval_fleet_tonnage_mt                 float64
aircraft_carriers                              int64
helicopter_carriers                            int64
submarines                                     int64
destroyers                                     int64
frigates                                       int64
corvettes                                      int64
coastal_patrol_craft                           int64
mine_warfare_craft                             int64
defense_budget_usd                             int64
external_debt_usd                              int64
purchasing_power_parity_usd                    int64
foreign_exchange_and_gold_reserves_usd         int64
total_serviceable_airports                     int64
labour_force                                   int64
major_ports_and_terminals                      int64
total_merchant_marine_fleet                    int64
railway_coverage_km                            int64
roadway_coverage_km                           object
oil_production_bbl                             int64
oil_consumption_bbl                            int64
proven_oil_reserves_bbl                        int64
natural_gas_production_cum                   float64
natural_gas_consumption_cum                  float64
proven_natural_gas_reserves_cum              float64
coal_production_cum                          float64
coal_consumption_mt                            int64
proven_coal_reserves_cum                     float64
total_land_area_sq_km                          int64
coastline_coverage_km                          int64
border_coverage_km                             int64
waterway_coverage_km                           int64
dtype: object

In [11]:
df.to_csv('Military_clean_data.csv', index=False)